# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 761279bb119c9ccbf94b160c02854ce3c9a156877c2f5b8dc09edd94bb52efc92d9af7be6f45aeb48862d3626d791ae2c44a00d78dcc1e9681379eb03d3e3bb3

test:
  secret_key_base: 62273691103b34db5427d265d1c5fc427ec4427ed963167b3161643e12bff26162f682acc69de092217a57593d90a35dc8a6695bd931622f9f749b311cbfae96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
